---
- hosts: localhost

  collections:
  - kubernetes.core
  tasks:
  - name: Get a list of all pods from any namespace
    kubernetes.core.k8s_info:
      host: https://api.ocp4.systex4.local:6443
      kind: Pod
    register: pod_list

  - name: create k8s pod
    kubernetes.core.k8s:
      src: deployment.yaml
      namespace: dev-game-app
      state: present

  - name: service create
    kubernetes.core.k8s:
      src: service.yaml
      namespace: dev-game-app
      state: present

# - name: Get a list of all pods from any namespace
#   kubernetes.core.k8s_info:
#    kind: Pod
#    register: pod_list



  
