---
- name: Deploy monitoring
  hosts: rhel
  become: true

  # module_defaults:
  #   ansible.posix.firewalld:
  #     permanent: true

  tasks:
   
    # - name: Include redhat.rhel_system_roles.cocpit
  
    # - name: Copy files/cockpit.conf to /etc/cockpit/
     
    # name: Restart cockpit service

    # name: Allow cockpit through firewall

    # - name: cấu hình firewalld cho kết nối httpd

    # - name: cài đặt httpd
  
    # - name: thay đổi thông tin SElinux enforcing
     
    - name: cài đặt web server
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true






 


   


      
