---
- name: install and start Apache
  hosts: solaris
  vars_files:
    - "vars/{{ ansible_os_family }}.yml"
   
  tasks:
    - name: install Apache on Solaris
      pkg5: name=web/server/apache-24
      when: ansible_os_family == "Solaris"
 
    - name: install Apache on RHEL
      yum:  name=httpd
      when: ansible_os_family == "RedHat"
 
    - name: start Apache
      service: name={{ apache }} state=started
