---
- name: back up config and look at device health indicators on ios devices
  hosts: ios
  tasks:

  - name: backup the device configuration
    cisco.ios.ios_config:
      backup: true
  
  

#   ios_config:
#    backup: yes

  - name: look at device health indicators
    ios_command:
      commands:
      # this provides hostname and uptime
      - sh ver | include uptime
      - sh ip domain
      - sh clock
      - sh ip name-server
      - sh proc mem | include Total
    register: results

  - name: show results
    debug:
      msg: "{{ item }}"
    loop: "{{ results.stdout_lines }}"

  - name: thêm vlan 10 
  

  
  - name: tạo acl 10 
    cisco.ios.ios_config:
      lines:
        - 10 permit ip host 1.1.1.1 any log
        - 20 permit ip host 2.2.2.56 any log
        - 30 permit ip host 3.3.3.84 any log
        - 40 permit ip host 4.4.4.112 any log
        - 50 permit ip host 5.5.5.140 any log
      parents: ip access-list extended test
      before: no ip access-list extended test
      match: exact
  
  

  