---
- name: Harden linux systems
  hosts: node2.example.com
  become: true
  vars:
    harden_firewall: false
    harden_time: false
    harden_ssh: false
    harden_pci: false

  tasks:

    - name: Apply CIS Baseline
     
      ansible.builtin.include_role:
        name: Redhatofficial.rhel7_cis
        
