---
- name: Deploy monitoring
  hosts: rhel
  become: true

  # module_defaults:
  #   ansible.posix.firewalld:
  #     permanent: true

  tasks:
   
    - name: Include redhat.rhel_system_roles.cocpit
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.cocpit
      vars:
        cocpit_profiles:
          - name: ovirt-engine-dns
            dns: ovirt-engine
            profile: systemd
            command: monitor
            interval: '300'
            retry: '3'
            timeout: '300'
          - name: ovirt-fetch-logs
            fetch_logs: true
            log_dir: /var/log/ovirt-engine-dns
            profile: systemd
            command: monitor
            interval: '300'
            retry: '3'
            timeout: '300'
    
  
    # - name: Copy files/cockpit.conf to /etc/cockpit/
    
         
    # - name: Restart cockpit service

    # name: Allow cockpit through firewall

    - name: install httpd
  
    - name: change SElinux enforcing
      ansible.posix.selinux:
        policy: targeted
        state: enforcing
      register: selinux
     
    - name: cài đặt web server
      ansible.builtin.package:
        name: httpd
        state: latest
    
    - name: Install postgresql-server
      ansible.builtin.package:
        name: postgresql-server
        state: latest
    
    
     
    
    







 


   


      
