---
- name: Linux hardening
  hosts: node3.example.com
  become: true
  gather_facts: yes

  tasks:
    - name: Ensure firewall package is installed
      ansible.builtin.yum:
        name: firewalld
        state: present

    - name: Ensure firewall service is up and running
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes
